// ERRORS:(FIX THESE LATER...)

// 1) ALL THE REPLIES GOING TO THAT GUESS THE MOVIE TWEET, NO TWEET GOING TO THE PREVIOUS STATE OF SETREPLY i.e
//    PREVIOUS TWEET KE REPLY MAI SET HO RHA HAI NEXT TWEET KA REPLY BHI, SOME STATE PROBLEMS HERE IG, FIX IT, 
//    SEE THE CREATEREPLY METHOD IN TWEETSERVICEIMPL...
// 1.1) REPLIES SHOULD NOT BE SEEN IN HOMEPAGE, THEY SHOULD BE ONLY IN REPLY SECTION.
// 1.2) REPLIES WITHOUT IMAGES SHOULD NOT HAVE THAT GREY BOX.
// 1.3) ALL TWEETS/TWEET CARD IN HOMESECTION SHOWING SAME NAME...
// KHUD KO FOLLOW KASIE KAR RHA HAI, AND USER PROFILE NOT SHOWING USER TWEEETS..., ALL TWEETS GOING TO SANGWAN A/C 

// 2) AXIOS ERROR COMING WHILE REPLING TO A TWEET
// 3) GIVEN ID MUST NOT BE NULL IN BACKEND
// 4) PROFILE BIO, LOCATION, ETC NOT UPDATING.

// 5) INTEGRATE PAYMENT USING RAZOR PAY
// 6) SHOULD I MAKE THAT E-COMMERCE APP??? LETS SEE, ILL BUY SOURCE CODE OF IT...

// 7) put menu of download file and see how to download it, and bookmark blue when clicked.
// 8) make it respnsive
// 9) add replies, likes, etc tabs in profile section..

